% MATLAB Script to create the .geo mesh file for Antarctica
% Adapted from Makegeo for WSB (Wilkes Subglacial Basin)
% Yu Wang
% October 2021, at BNU
% Updated in April 2026 for Antarctica full coastline boundary
% -Infinite Progress-
%
% Antarctica is a complete closed coastline with NO inland boundary.
% The entire boundary is a single closed loop representing the coastline.
%
% Input:  Antarctica_Boundary_clean.csv (from Check_csv.m)
% Output: mesh2D_Antarctica.geo (for Gmsh -> Elmer)
%
% Coordinate system: EPSG:3031 (Antarctic Polar Stereographic)

clc; clear; close all;

%% Step 1: Read the cleaned boundary data

dataTable = readtable('Antarctica_Boundary_clean.csv');
xCoords = dataTable.x;
yCoords = dataTable.y;
nPoints = length(xCoords);

fprintf('=== Makegeo Antarctica ===\n');
fprintf('Loaded %d boundary points from Antarctica_Boundary_clean.csv\n', nPoints);

%% Step 2: Visual inspection

figure('Name', 'Antarctica Boundary', 'Position', [100 100 800 800]);
plot(xCoords, yCoords, 'b-', 'LineWidth', 0.5);
hold on;
plot(xCoords(1), yCoords(1), 'go', 'MarkerSize', 10, 'MarkerFaceColor', 'g');
title('Antarctica Coastline Boundary');
xlabel('X (m, EPSG:3031)');
ylabel('Y (m, EPSG:3031)');
legend('Coastline', 'Start/End point');
axis equal; grid on;

%% Step 3: Configure mesh parameters

% Grid resolution in meters
gridResolution = 10000.0;

% Maximum points per Spline segment (Gmsh handles ~5000 well)
maxPtsPerSpline = 5000;

fprintf('Grid resolution: %.0f m\n', gridResolution);

%% Step 4: Write the .geo file

geoFileName = 'mesh2D_Antarctica.geo';
geoFile = fopen(geoFileName, 'w');

% --- Header ---
fprintf(geoFile, '// Antarctica coastline mesh\n');
fprintf(geoFile, '// Generated by Makegeo_Antarctica.m\n');
fprintf(geoFile, '// %d boundary points, closed coastline loop\n', nPoints);
fprintf(geoFile, '// Coordinate system: EPSG:3031 (Antarctic Polar Stereographic)\n\n');

% --- Grid resolution ---
fprintf(geoFile, 'lc = %.1f;\n\n', gridResolution);

% --- Points ---
fprintf(geoFile, '// === Points (%d) ===\n', nPoints);
for i = 1:nPoints
    fprintf(geoFile, 'Point(%d) = {%.5f, %.5f, 0.0, lc};\n', i, xCoords(i), yCoords(i));
end

% --- Splines (split into chunks for Gmsh robustness) ---
% Each Spline segment shares endpoints with its neighbours.
% The last segment closes back to Point(1).

nSegments = ceil(nPoints / maxPtsPerSpline);
fprintf(geoFile, '\n// === Splines (%d segments) ===\n', nSegments);
fprintf('Splitting coastline into %d Spline segments (max %d pts each)\n', ...
    nSegments, maxPtsPerSpline);

splineIds = zeros(nSegments, 1);

for seg = 1:nSegments
    splineId = seg;
    splineIds(seg) = splineId;

    % Determine point range for this segment
    startPt = (seg - 1) * maxPtsPerSpline + 1;
    if seg < nSegments
        endPt = seg * maxPtsPerSpline + 1;  % overlap by 1 for continuity
    else
        endPt = nPoints;  % last segment ends at the final point
    end

    % Clamp endPt
    endPt = min(endPt, nPoints);

    % Build the point index list
    ptIndices = startPt:endPt;

    % For the last segment, close the loop back to Point(1)
    if seg == nSegments
        ptIndices = [ptIndices, 1];
    end

    % Write the Spline definition
    fprintf(geoFile, 'Spline(%d) = {', splineId);
    for j = 1:length(ptIndices)
        if j < length(ptIndices)
            fprintf(geoFile, '%d, ', ptIndices(j));
            % Line break every 20 values for readability
            if mod(j, 20) == 0
                fprintf(geoFile, '\n    ');
            end
        else
            fprintf(geoFile, '%d', ptIndices(j));
        end
    end
    fprintf(geoFile, '};\n');

    fprintf('  Spline(%d): points %d to %d', splineId, ptIndices(1), ptIndices(end));
    if seg == nSegments
        fprintf(' (closes to Point 1)');
    end
    fprintf('\n');
end

% --- Line Loop (combine all Spline segments) ---
fprintf(geoFile, '\n// === Line Loop (closed coastline) ===\n');
fprintf(geoFile, 'Line Loop(%d) = {', nSegments + 1);
for i = 1:nSegments
    if i < nSegments
        fprintf(geoFile, '%d, ', splineIds(i));
    else
        fprintf(geoFile, '%d', splineIds(i));
    end
end
lineLoopId = nSegments + 1;
fprintf(geoFile, '};\n');

% --- Plane Surface ---
surfaceId = lineLoopId + 1;
fprintf(geoFile, '\n// === Plane Surface ===\n');
fprintf(geoFile, 'Plane Surface(%d) = {%d};\n', surfaceId, lineLoopId);

% --- Physical Groups ---
% Antarctica: only coastline boundary (no inland boundary)
physLineId = surfaceId + 1;
physSurfId = physLineId + 1;

fprintf(geoFile, '\n// === Physical Groups ===\n');
fprintf(geoFile, '// Physical Line: coastline boundary (all segments)\n');
fprintf(geoFile, 'Physical Line(%d) = {', physLineId);
for i = 1:nSegments
    if i < nSegments
        fprintf(geoFile, '%d, ', splineIds(i));
    else
        fprintf(geoFile, '%d', splineIds(i));
    end
end
fprintf(geoFile, '};\n');

fprintf(geoFile, '// Physical Surface: Antarctica ice sheet\n');
fprintf(geoFile, 'Physical Surface(%d) = {%d};\n', physSurfId, surfaceId);

fclose(geoFile);

%% Step 5: Summary

fprintf('\n=== .geo file created: %s ===\n', geoFileName);
fprintf('  Points:           %d\n', nPoints);
fprintf('  Spline segments:  %d\n', nSegments);
fprintf('  Line Loop ID:     %d\n', lineLoopId);
fprintf('  Plane Surface ID: %d\n', surfaceId);
fprintf('  Physical Line ID: %d  (coastline)\n', physLineId);
fprintf('  Physical Surface: %d  (ice sheet)\n', physSurfId);
fprintf('  Grid resolution:  %.0f m\n', gridResolution);
fprintf('\nNext steps:\n');
fprintf('  1. gmsh mesh2D_Antarctica.geo -2    (generate 2D mesh)\n');
fprintf('  2. ElmerGrid 14 2 mesh2D_Antarctica.msh  (convert for Elmer)\n');
